docker-compose-yaml: docker-compose.yml

project: demo-lullabot-drupalfull

#lagoon-sync:
#  mariadb:
#    config:
#      hostname: database
#      username: tugboat
#      password: tugboat
#      port: 3306
#      database: tugboat
#  files:
#    config:
#      sync-directory: "./web/sites/default/files"
#  drupalconfig:
#    config:
#      syncpath: "./config/sync"

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: IF no Drupal installed and we are not main branch, sync from main branch
        command: |
            if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ] && [[ "$LAGOON_GIT_BRANCH" != "main" ]]; then
                # no drupal installed, sync DB from main branch
                drush -y sql-sync @lagoon.demo-lullabot-drupalfull-main @self
                drush -y rsync @lagoon.demo-lullabot-drupalfull-main:%files @self:%files
                drush -y cr
            fi
        service: cli
        shell: bash
    # Enable once config sync has been setup.
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush updb
        command: drush -y updb
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  main:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/30 * * * *"
        command: drush cron
        service: cli
