services:
  # cli container, will be used for executing composer and any local commands (drush, drupal, etc.)
  cli:
    # image: uselagoon/php-8.1-cli-drupal:latest
    image: tugboatqa/php:8.1-apache
    checkout: true

  nginx:
    # image: uselagoon/nginx-drupal:latest
    image: tugboatqa/nginx:stable
    checkout: true
    depends: cli
    commands:
      init:
        - echo "alias ll='ls -la'" >> /root/.bashrc
        - echo "export PATH=$PATH:${TUGBOAT_ROOT}/vendor/bin" >> /root/.bashrc
        - docker-php-ext-install opcache
        - mkdir -p "${TUGBOAT_ROOT}/files-private" "${TUGBOAT_ROOT}/config"
      update:
        - composer install --optimize-autoloader
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        - cp "${TUGBOAT_ROOT}/.tugboat/default.settings.php" "${DOCROOT}/sites/default/settings.local.php"
        - ln -snf "${TUGBOAT_ROOT}/files-private" "${DOCROOT}/../files-private"
        - mkdir -p "${DOCROOT}/sites/default/files"
        - chgrp -R www-data "${DOCROOT}/sites/default/files"
        - find "${DOCROOT}/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;

  php:
    # image: uselagoon/php-8.1-fpm:latest
    image: tugboatqa/php:8.1-fpm
    default: true
    depends: [cli,nginx,mariadb]

  mariadb:
    # image: uselagoon/mariadb-10.6-drupal:latest
    image: tugboatqa/mariadb:10.6

  solr:
    # image: uselagoon/solr-8-drupal:latest
    image: tugboatqa/solr:8
    depends: cli

  redis:
    # image: uselagoon/redis-6:latest
    image: tugboatqa/redis:6
